In [ ]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

In [ ]:
df = pd.read_csv("data/dataset_copy.csv").drop(["track_num"],axis=1).dropna(subset = ['track_name'])
df.head()

,track_id,artist_name,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson & ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [ ]:
df["artist_track_name"] = df["artist_name"] + " - "+ df["track_name"]
df

,track_id,artist_name,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre,artist_track_name
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Gen Hoshino - Comedy
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Ben Woodward - Ghost - Acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson & ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Ingrid Michaelson & ZAYN - To Begin Again
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Kina Grannis - Can't Help Falling In Love
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Chord Overstreet - Hold On
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,...,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Rainy Lullaby - Sleep My Little Boy
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,...,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Rainy Lullaby - Water Into Light
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,...,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Cesária Evora - Miss Perfumado
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,...,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Michael W. Smith - Friends
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,...,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Cesária Evora - Barbincor

In [ ]:
df.drop_duplicates(subset=['artist_track_name'], keep=False)
df=df.groupby('genre').sample(frac=.2).reset_index(drop=True)
df

,track_id,artist_name,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre,artist_track_name
0,2PTzfXh5Ut3hjRrWGyafz6,Stephen Speaks,No More Doubt,Passenger Seat,64,274480,False,0.523,0.554,7,...,1,0.0303,0.7490,0.000003,0.3230,0.7690,152.979,4,acoustic,Stephen Speaks - Passenger Seat
1,0v0pc1lIt5p6EBX7pnfOGF,Ross Copperman,Holding On and Letting Go LP,Holding On and Letting Go,49,317441,False,0.486,0.555,2,...,1,0.0271,0.8180,0.002690,0.1090,0.0992,77.987,4,acoustic,Ross Copperman - Holding On and Letting Go
2,4qTHoIp62ngNDpUJwW3hZ7,Boyce Avenue,"Cover Sessions, Vol. 6",Can’t Help Falling in Love,57,131000,False,0.402,0.197,5,...,1,0.0295,0.8580,0.000001,0.1140,0.1480,100.044,3,acoustic,Boyce Avenue - Can’t Help Falling in Love
3,33JX2be3eKVhl5xk8YQhVc,Ray LaMontagne,Till The Sun Turns Black,Empty,48,317280,False,0.482,0.381,2,...,1,0.0311,0.4550,0.002950,0.1140,0.4200,81.712,4,acoustic,Ray LaMontagne - Empty
4,6OCsvPU6P84wJ0erggCRv4,Albert King,pov: you have a holly jolly christmas,Christmas Comes But Once A Year,0,272640,False,0.687,0.494,1,...,1,0.0505,0.3240,0.000055,0.0867,0.6210,93.269,1,acoustic,Albert King - Christmas Comes But Once A Year
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22795,4WbOUe6T0sozC7z5ZJgiAA,Lucas Cervetti,Frecuencias Álmicas en 432hz,"Frecuencia Álmica, Pt. 4",22,305454,False,0.331,0.171,1,...,1,0.0350,0.9200,0.022900,0.0679,0.3270,132.147,3,world-music,"Lucas Cervetti - Frecuencia Álmica, Pt. 4"
22796,5QT13TE0vN29dYa8Ifkz0A,Leeland & TAYA,Heart & Flesh,Heart & Flesh,55,431520,False,0.270,0.386,2,...,1,0.0301,0.2690,0.000001,0.0995,0.1510,131.876,3,world-music,Leeland & TAYA - Heart & Flesh
22797,4PYOh644yKjYyvyVUHqcof,All Sons & Daughters & Leslie Jordan & David L...,Live,Great Are You Lord - Live,60,290413,False,0.390,0.457,9,...,1,0.0327,0.0874,0.000009,0.1230,0.1450,143.977,3,world-music,All Sons & Daughters & Leslie Jordan & David L...
22798,6hzaKM08IZOAWMoITG9UjV,Raul Paz,Ven Ven,No Me Digas Que No,25,207866,False,0.773,0.634,5,...,0,0.0754,0.3810,0.000000,0.1630,0.5650,135.991,4,world-music,Raul Paz - No Me Digas Que No
22799,2s1a8wNeH6IiOSowWj9veS,Audrey Assad,Inheritance,Be Thou My Vision,53,213730,False,0.194,0.324,1,...,1,0.0338,0.9020,0.196000,0.1090,0.1570,169.758,3,world-music,Audrey Assad - Be Thou My Vision

In [ ]:
pickle.dump(df, open('pickle/df_smaller.pkl','wb'))

In [ ]:
# since genre is in the form of different unique genres
mylist=df['artist_track_name'].to_list()
mylist = list(dict.fromkeys(mylist))
pickle.dump(mylist, open('pickle/mylist_smaller.pkl','wb'))
mylist

['Stephen Speaks - Passenger Seat',
 'Ross Copperman - Holding On and Letting Go',
 'Boyce Avenue - Can’t Help Falling in Love',
 'Ray LaMontagne - Empty',
 'Albert King - Christmas Comes But Once A Year',
 'Ben Rector - Brand New',
 'Amber Leigh Irish - Save Your Tears - Acoustic',
 'Zack Tabudlo - Habang Buhay',
 'Ramshackle Glory - Of Ballots and Barricades - Live',
 'Andrew Belle - Pieces',
 "Gabrielle Aplin - Please Don't Say You Love Me",
 'Frank Turner - Little Life',
 "JJ Heller - It'll Be Alright",
 'Kina Grannis - Iris',
 'Ingrid Michaelson - Everybody',
 'The Mayries - Overpass Graffiti',
 'The Bridge City Sinners - Laugh While You Can',
 'Boyce Avenue & Tyler Ward - Fix You',
 'Keisha White - The Weakness In Me',
 "Mother's Daughter & Beck Pete - A Sky Full of Stars",
 'Tyler Ward & Karis & Ray Lorraine - Love Story',
 'Jason Mraz & Meghan Trainor - More Than Friends (feat. Meghan Trainor)',
 'Anna Hamilton - Bad Liar',
 'Parachute - The Mess I Made',
 'Aoi Teshima - こころをこめて',
 'JJ Heller - In the Morning',
 'Pigeon Pit - Peach',
 'Sara Farell - Dancing With A Stranger',
 'Rachael Yamagata - Is It You',
 'Canyon City - Between the Stars',
 'Aimyon - Naked Heart',
 'The Civil Wars - To Whom It May Concern',
 'Sara Farell - Issues - Acoustic',
 'Angelina Cruz - Hanggang Kailan (Umuwi Ka Na Baby)',
 'AJJ - Darkest Heart',
 'Kaiak & Viktoria Tolstoy - Autumn Breeze',
 'Masaharu Fukuyama - 追憶の雨の中 (Original Version)',
 'Boyce Avenue - Beautiful Soul',
 'Masaharu Fukuyama - Message (Original Version)',
 "Brandon Chase - I'll Say I Do",
 'Filip Nordin - Stitches',
 'Ray LaMontagne - Three More Days',
 'Stephen Speaks - Out of My League',
 'Front Porch Step - So Help Me God',
 'Aberola - Si Te Vas',
 'Kitri - Hikare Inochi',
 'Days N Daze - Comfort epershand Control',
 'Ray LaMontagne - Such A Simple Thing',
 'Greg Laswell - Comes And Goes (In Waves)',
 'Zack Tabudlo - Pero',
 "We The Heathens - When It's Gone",
 'A Great Big World - Kaleidoscope',
 'Jason Mraz - Sleep All Day',
 'Yosui Inoue & Tamio Okuda - 月ひとしずく',
 "Joshua Radin - You're My Home",
 'Jason Mraz - I Won’t Give Up',
 'Matthew Perryman Jones - Living in the Shadows',
 'KT Tunstall - Hold On',
 'Rosie Thomas & The Shins & Sufjan Stevens & Josh Ottum - Always Be My Baby',
 'Keisha White - The Weakness in Me',
 "Suy Galvez - You've Got a Friend",
 'Chris Cresswell - Arrythmic Palpitations',
 'Us The Duo - No Matter Where You Are - Wedding Version',
 "Kris Allen - Live Like We're Dying",
 'Days N Daze - Goodbye Lulu',
 'Sara Farell - Teenage Dream',
 'Kurei - Paasa',
 'Jason Mraz - Who Needs Shelter',
 'Luther Allison - Life Is A Bitch',
 'Callum J Wright - Somebody Else - Acoustic',
 'Ben Rector - It Would Be You',
 'Takehara Pistol - Amazing Grace',
 'Boyce Avenue & Sarah Hyland - Closer',
 'JJ Heller - Neighbor (Piano Version)',
 'Kina Grannis - You Are My Sunshine',
 'Lusaint - Use Somebody - Acoustic',
 'Eastmountainsouth - So Are You To Me',
 'John Adams - You’re Beautiful - Acoustic',
 'Masaharu Fukuyama - 約束の丘',
 'Andrew Foy & Renee Foy - Let Her Go',
 'Naotaro Moriyama - さくら - 二〇一九',
 'Canyon City - So Are We',
 'Boyce Avenue & Fifth Harmony - Mirrors',
 'Us The Duo - No Matter Where You Are',
 'Guus Dielissen - Moth To A Flame - Acoustic Instrumental',
 'Us The Duo - Already Mine',
 'Ysabelle Cuevas - I Like Me Better',
 'Zee Avi - Bitter Heart',
 'Eddie Vedder - Photographs',
 'Mone Kamishiraishi - 世界中の誰よりきっと',
 'Aimyon - 君はロックを聴かない',
 'Chord Overstreet & Deepend - Hold On - Remix',
 'Aron Wright - You & Me (The Wildfire)',
 "Brett Dennen & Benedict Cumberbatch - Can't Keep It Inside",
 'Joseph Sullinger - What a Wonderful World',
 'Jonah Baker - Running Up That Hill (A Deal With God) - Acoustic',
 'Brandi Carlile & Lucius - You and Me on the Rock',
 'Covers Culture & Acoustic Covers Culture & Lounge Covers Culture Of Popular Songs - Lost Cause - Acoustic Covers Versions of Popular Songs',
 "John Frusciante - Song To Sing When I'm Lonely",
 'KT Tunstall - Lonely This Christmas',
 'Takehara Pistol - 一等賞',
 'The Cameron Collective - The Greatest Showman - Rewrite The Stars (Acoustic)',
 'Days N Daze - Fall Out',
 'Ron Pope - A Drop In the Ocean',
 'Boyce Avenue - Rise',
 'John Frusciante & Josh Klinghoffer - The Afterglow',
 'Donovan Woods - Seeing Other People',
 'Joshua Hyslop - The Spark - Bonus Track',
 'Kina Grannis - Issues',
 'Canyon City - Alone with You',
 'Chuck Ragan - The Boat',
 'Eddie Vedder & Nusrat Fateh Ali Khan - The Long Road',
 'JJ Heller - You Already Know',
 'Rail Yard Ghosts - A Month from Now',
 'Us The Duo - Shotgun',
 'Frank Turner - Rivers',
 'Frank Turner - Untainted Love',
 'AJJ - Linda Ronstadt',
 'Boyce Avenue & Bea Miller - See You Again',
 'Boyce Avenue - Someone Like You',
 'The Perishers - Trouble Sleeping',
 'Jason Mraz & Colbie Caillat - Lucky',
 'Gail Blanco - Close to You',
 'Richard Walters - July Bones',
 'Boyce Avenue - Scared to Be Lonely',
 "Gabrielle Aplin - Don't Know What I Want",
 'Penny and Sparrow & Stephanie Briggs - Duet (feat. Stephanie Briggs)',
 'Motohiro Hata - ひまわりの約束',
 'Roses & Frey - Dance Monkey',
 "Mindy Smith - It's Amazing",
 'Brandi Carlile - The Joke',
 'Masaharu Fukuyama - KISSして',
 'Nathan Angelo - She’s The Song',
 'Masaharu Fukuyama - 明日の☆SHOW',
 'Jason Mraz - Love Someone',
 'AJJ - I Am So Mad at You',
 'Suy Galvez - Your Song',
 'Little Walter - My Babe',
 'Jon Bryant - Headphones',
 'Bailey Jehl - 21 Guns',
 'Vendredi & Chrissy Dave - Seven Nation Army - Acoustic Covers Versions of Popular Songs',
 'Albert Collins - Cold, Cold Feeling',
 'Matt Nathanson - Laid',
 'Daniel Robinson - Here With Me - Acoustic',
 'Brandi Carlile - Speak Your Mind (From the Netflix Series "We The People")',
 'The Rescues - Teenage Dream',
 'Guus Dielissen - As It Was - Acoustic Instrumental',
 'Allman Brown - Ancient Light',
 'Masaharu Fukuyama - あの夏も 海も 空も',
 'Jess Penner - Sweeter',
 'JJ Heller - Better',
 'Eddie Vedder & Cat Power - Tonight You Belong To Me',
 "Covers Culture & Acoustic Covers Culture & Lounge Covers Culture Of Popular Songs - You're Not Sorry - Acoustic Covers Versions of Popular Songs",
 'Harley Poe - Whiny Bitch',
 'Frank Turner - Bob',
 'KT Tunstall - Black Horse And The Cherry Tree',
 'Kina Grannis - For Now',
 'The Civil Wars - Poison & Wine',
 'EJ De Perio - Tama Na',
 'Gabrielle Aplin - So Far so Good',
 'Johnnyswim - Drunks',
 'Zack Tabudlo - Heart Can’t Lose',
 'Masayoshi Yamazaki - アンダルシアに憧れて',
 'Gabrielle Aplin - Night Bus',
 'Mark Oblea - Kabilugan Ng Buwan',
 'Matt Costa - I Bet On Flying High',
 'Gabrielle Aplin - Start of Time',
 'JJ Heller - Ordinary Days',
 'Phillip LaRue - Sweet Love',
 'Michael Logen - Darkness Within',
 'Ingrid Michaelson - You And I',
 'JJ Heller - Make You Feel My Love',
 "Jae Hall - Sweet Child O' Mine - Acoustic",
 'Jonah Baker - A Thousand Years - Acoustic',
 'Gabrielle Aplin - Magic',
 'Boyce Avenue & Connie Talbot - Can You Feel the Love Tonight',
 'Marc Broussard - Rocksteady',
 'Ichiko Aoba - Asleep Among Endives',
 'Todd Carey & Ariza & Chuck Leavell - Higher Love',
 'Frank Turner - Perfect Government',
 'Caleb Santos & Viva Music Publishing Inc. - I Need You More Today',
 'Jon Bryant - Wilderness',
 'Days N Daze - Days n Daze of Our Lives',
 'Unkle Bob - Swans',
 "Chord Overstreet - What's Left of You",
 'Kurt Cobain - Burn The Rain',
 'Pigeon Pit - Tall Cans',
 'Megan Davies - See You Again, Love Me Like You Do, Sugar - Acoustic Mashup',
 'Grace Petrie - Northbound',
 'Joy Williams - Front Porch',
 'Brendan James - Yellow Lines',
 'Sakura Fujiwara - Someday',
 'The Perishers - My Heart',
 'A Great Big World - Already Home',
 'Hanare Gumi - PEOPLE GET READY',
 'Frank Turner - Eat the Meek',
 'JJ Heller - Neighbor',
 'Takehara Pistol - サンサーラ',
 'Gabrielle Aplin - The Power of Love',
 'Jorge Drexler - La luna de espejos',
 'Los Amigos Invisibles - Goldmember',
 'Africania - Cachoeira',
 "Jor'dan Armstrong & Tim Bowman Jr. - Pull Me Through",
 'Orchestra Baobab - Boulmamine',
 'Jorge Drexler - La aparecida',
 'Rehmahz & Limoblaze - Victory',
 'Jorge Drexler - Al Otro Lado Del Río (342 Amazônia ao Vivo no Circo Voador)',
 'Jorge Drexler - Durante',
 'The Souljazz Orchestra - Soleil Couchant',
 'Ikebe Shakedown - Tame the Beats',
 "Jor'dan Armstrong - I'm Wit It",
 'Buyepongo - Musica Alegre',
 'Newen Afrobeat - Vuela Junto a Mí',
 'Orchestra Baobab - Aduna Diaroul Niawo',
 'Louis Pascal - Life of Grace',
 'Victor Rice - Tema',
 'Jackie Mittoo - Hot Tamale',
 'Calle 13 - Pi-di-di-di',
 'BaianaSystem - Duas Cidades',
 'Romperayo - Que Tumba',
 'Warsaw Afrobeat Orchestra & Bosq - Only Now - Bosq Remix',
 'Foli Griô Orquestra & Carlos Malta & Dofono de Omulu & Ekedi Nicinha - Awo',
 "Lo'Jo & Vincent Ségal & Robert Wyatt - Tout est fragile",
 "Los Amigos Invisibles & Oscar D'León - Sabrina (feat. Oscar D'León)",
 "Speedometer & Ria Currie - You've Made Me So Very Happy featuring Ria Currie",
 'Greyboy & Bing Ji Ling - So Good',
 'The Sorcerers - Beneath the City of the Monkey God',
 'Criolo - Samba Sambei (Dub Mix)',
 'Criolo - Espiral de Ilusão',
 'La Misa Negra - Me Voy Pa’ Porce',
 'Afrocidade - Direto de Camaçacity',
 'Criolo - Demorô',
 'Criolo - Cria de Favela',
 'Orgone - Nasty Hats',
 "Jor'dan Armstrong - EMOTIONS",
 'A Mose - Faraway',
 'Jorge Drexler - La edad del cielo',
 'Calle 13 & Silvio Rodríguez - Ojos Color Sol (feat. Silvio Rodríguez)',
 'BaianaSystem - Chapéu Panamá',
 'BaianaSystem - O Carnaval Quem É Que Faz?',
 'The Bamboos & Washington - The Wilhelm Scream',
 'Ali Farka Touré - Savane',
 "Jor'dan Armstrong - God Got Me",
 'Mandrill - Hang Loose',
 'BaianaSystem - Navio',
 "cacique'97 - Jorge de Capadócia",
 'Samuca e a Selva & Criolo - Cais',
 'Menahan Street Band - Queens Highway',
 'Gyedu-Blay Ambolley - Ketan',
 'Jlyricz - Searching',
 'Criolo & Emicida - Não Existe Amor Em SP - Live',
 'The New Mastersounds - Freckles',
 'Jorge Drexler - Codo Con Codo',
 'Money Chicha - Quieren Efectos',
 'Ondatrópica - Malaria',
 'BaianaSystem - Invisível',
 'ST-Saint - 4:ME',
 'Jungle Fire - Village Hustle',
 'Los Amigos Invisibles & Los Auténticos Decadentes - Aquí Nadie Esta Sano (feat. Los Auténticos Decadentes)',
 'A Mose & Marizu - Follow me',
 'Jorge Drexler - Paisaje lunar',
 'Romperayo - Asi No Se Puede Muchaches',
 "Lefties Soul Connection - It's Your Thing / Hey Pocky a-Way",
 'Ikebe Shakedown - Not Another Drop (Reprise)',
 'Azarel & Leor - Who Am I (Psalm 8:4)',
 'Orchestra Baobab - Utrus Horas',
 'Juanafé & Demian Rodríguez - Fuiste un Trozo de Hielo en la Escarcha',
 'Samuca e a Selva - Passeando em Mim',
 'Soothsayers - Nothing Can Stop Us',
 'Juanafé - El Volcán',
 'Los Amigos Invisibles - Cuchi-cuchi',
 'Los Amigos Invisibles & Superthriller - Give us your money (feat. Superthriller)',
 'Plastilina Mosh - Shampoo',
 "Jor'dan Armstrong - Tomorrow",
 'Nero X - Yawa Dey',
 'Sarah Téibo & Fred Hammond - Like a Child - Remix',
 'Timoneki - Alma',
 'BaianaSystem & Tonho Matéria - Catraca',
 'Eben - Victory',
 'BaianaSystem - Vinheta Baiana',
 'Orquestra Brasileira de Música Jamaicana - O Guarani',
 'Samuca e a Selva - Jussara',
 'Criolo - Yemanjá Chegou',
 'Greyboy & Nino Moschella - Love',
 'Limoblaze & Dj Horphuray - Your Love',
 'Calle 13 - El Avión Se Cae',
 'Voilaaa & Lass - Mandjou',
 'Calle 13 - Se Vale To-To',
 'Voilaaa - Jungle Fire',
 'Ikebe Shakedown - Tujunga',
 'Mandrill - Mango Meat',
 'BaianaSystem & Orquestra Afrosinfônica - Fogo (Versão Estendida)',
 'Vaudou Game - Elle décide',
 'Los Amigos Invisibles - Si Estuvieras Aquí',
 'Sharyn - Anyway',
 'Criolo - Nas Águas',
 'Tony Allen - Ewa',
 'Criolo & Rael - Tô Pra Ver',
 'Criolo - Fellini',
 'Tony Allen - Ikeja Roads',
 'Plastilina Mosh - Kinkinzazo',
 'TJ Cream & Marko - Hard Talk',
 'Buena Onda Reggae Club - Song for Rollins',
 "The Bamboos - I Don't Wanna Stop",
 'Sharyn & Triple O - Life',
 'Plastilina Mosh - Human Disco Ball',
 'Plastilina Mosh - Te Lo Juro Por Madonna (Si Omba Ta Gueno)',
 'BaianaSystem - Barravenida, Pt. 2',
 'William Onyeabor - Better Change Your Mind - Mixed',
 'Jorge Drexler - No te creas',
 'Chico Mann & Captain Planet - Ariwoko',
 'Brownout & Brown Sabbath & Alex Maas - Hand of Doom',
 'BaianaSystem - Barbatana',
 'Antibalas - Talkatif',
 'Cymande - Dove',
 'Manu Dibango - Dikalo - Remix 97',
 'The Shaolin Afronauts - Baie de Sangareya',
 'El Hijo De La Cumbia - La Mara Tomaza',
 'Orquestra Brasileira de Música Jamaicana - Cotidiano',
 'The Bamboos - Tighten Up',
 'BaianaSystem & Thiago França - Reza Frevo',
 'Plastilina Mosh - Oxidados',
 'Eddie Neblett - Stepping Out',
 'Sarah Téibo & Sigag Lauren & Paola Carla - Belongs to You - EDM Remix',
 'TJ Cream - The Vibe',
 'Los Amigos Invisibles - Reino Animal',
 'The New Mastersounds - You Mess Me Up',
 'Mandrill & Michael Masser - Ali Bombaye (Zaire Chant) I',
 'Mandrill - Can You Get It',
 'QUITAPENAS - Guayabo',
 'BaianaSystem - BembaDub',
 "Menahan Street Band & Saundra Williams - There's a New Day Coming",
 'Juanafé & La Flor del Recuerdo - Si Tu Me Quisieras',
 'Abayomy Afrobeat Orquestra & Otto - Mundo Sem Memória',
 'Voilaaa & Hawa & Fouley Badiaga - Vampires',
 'BaianaSystem & Makavelli & Jaymitta - Nauliza',
 'Lafayette Afro Rock Band - Baba Hya - Remastered',
 'BaianaSystem - Raminho',
 'Eben & Nathaniel Bassey - No One Like You',
 'Limoblaze & Johnny Drille - This Loving',
 'Thiago França - Cumbia Cumbia',
 'The Budos Band - Budos Dirge',
 'BaianaSystem - Corneteiro Luís',
 'Plastilina Mosh - Mjlm',
 'Ebo Taylor & Uhuru-Yenzu - Love and Death',
 'El Michels Affair - Yennicita - Alternate Version',
 'Plastilina Mosh - Niño Bomba',
 'Metá Metá - Logun',
 'Criolo - Etérea',
 "Monophonics & Kelly Finnigan - It's Only Us",
 'Vaudou Game - Tata fatiguée',
 'Hugh Masekela - Makoti',
 'Star Feminine Band - Femme africaine',
 'Ikebe Shakedown - The Viking',
 'El Rego & Kill Emil - E Nan Mian Nuku',
 'Criolo - Freguês da Meia Noite',
 'Thiago França - Um samba pra John Coltrane',
 'Oba Reengy - Increase Comes From You',
 'J Prince - Must Reach',
 'Los Amigos Invisibles - La Que Me Gusta',
 "Jor'dan Armstrong - IN",
 'Plastilina Mosh - I´ve Got That Milton Pacheco Kinda Feeling - Melancolic Mix',
 'Samuca e a Selva - Chama Arteira',
 'Eben - Jesus at the Centre',
 'BaianaSystem & ÀTTØØXXÁ - Calamatraca (ÀTTØØXXÁ Remix)',
 'Criolo & Emicida - Grajauex - Live',
 'Orchestra Baobab - Clementine Jam',
 'Cymande - Bra',
 'BaianaSystem - Rádio África',
 'BaianaSystem & BNegão - Reza Forte',
 'Assagai - Telephone Girl',
 'BaianaSystem & Mahal Pita - Playsom (Mahal Pita Remix)',
 'Los Amigos Invisibles - Mango Cool',
 'Jackie Mittoo - Drum Song',
 'The Bongo Hop & Dafuniks - The Red Hill',
 'Los Amigos Invisibles - Viajero Frecuente del Amor',
 'BaianaSystem - Criado Mudou',
 'Monophonics - La La La Love Me',
 'TJ Cream & Beloved Music - Wisdom Seeker',
 'The Mauskovic Dance Band - Tuto Bay',
 'Jackie Mittoo - Freak Out',
 'Bacao Rhythm & Steel Band - Represent',
 'BaianaSystem - Oxe, Como Era Doce',
 'Gyedu-Blay Ambolley - Simigwa-Do',
 'The Budos Band - Black Hills',
 'BaianaSystem - Frevofoguete',
 'Greatman Takit - Story',
 'Mulatu Astatke & The Heliocentrics - An Epic Story',
 'Los Amigos Invisibles - Que Rico',
 'Juanafé - La Dormida',
 'Mulatu Astatke & The Heliocentrics - Chinese New Year',
 'Thee Commons - Juaneco Y La Negra',
 'Los Amigos Invisibles & Kinky - Anestesiada (feat. Kinky)',
 'The New Mastersounds & Eddie Roberts & Lamar Williams Jr. - Meet You In The Sunshine',
 'Estelares - Melancolía',
 'Guasones - Como un Lobo',
 'Newsboys - All I Want For Christmas Is You',
 'Charly García - Demoliendo Hoteles',
 'La Franela - Lo Que Me Mata',
 'Los Prisioneros - Estrechez De Corazón',
 'Julieta Venegas - Limón y Sal',
 'Blind Melon - No Rain',
 'The 1975 - When We Are Together',
 'Incubus - Drive',
 "The Killers & Ryan Pardey - Don't Shoot Me Santa",
 'Los Gardelitos - Cobarde para Amar',
 'Sam Tinnesz & Yacht Money - Play with Fire (feat. Yacht Money)',
 'Deftones - Change (In the House of Flies)',
 'The Neighbourhood - A Little Death',
 'Detonautas Roque Clube - Melhor Plantar o Bem',
 'Faith No More - Epic - Radio Edit',
 'Serú Girán - Canción De Alicia En El País - Remastered 2012',
 'The Score - Victorious',
 'Bandalos Chinos & Adan Jodorowsky - Departamento',
 'Panteon Rococo - Veinticinco Rosas',
 'Inspector & Panteon Rococo - Amargo Adios',
 'Eels - Christmas Is Going To The Dogs - From "Dr. Seuss\' How The Grinch Stole Christmas" Soundtrack',
 'Anthrax & Public Enemy - Bring The Noise',
 'Las Pastillas del Abuelo - Rocanrol N´n´n´',
 'Rob Zombie - Dragula',
 'Royal Blood - Honeybrains',
 'Stone Temple Pilots - Plush',
 'La Mosca Tse-Tse - Baila Para Mi',
 'Panteon Rococo - La Distancia',
 'Siouxsie and the Banshees - Halloween',
 'Siouxsie and the Banshees - Spellbound',
 'Rob Zombie - Superbeast',
 'Red Hot Chili Peppers - Black Summer',
 'Babasónicos - Como Eran Las Cosas',
 'Royal Blood - Figure It Out',
 'Os Paralamas Do Sucesso - Lourinha Bombril',
 'Sanctus Real - Confidence',
 'Comisario Pantera & Luis Humberto Navejas - Murasaki',
 'Creed - One Last Breath',
 'Charlie Brown Jr. - Tudo Que Ela Gosta De Escutar - Ao Vivo',
 'Caifanes - Será por Eso',
 'Jimmy Eat World - The Middle',
 'Skillet - Whispers in the Dark',
 "No Doubt - Don't Speak",
 'Duman - Her Şeyi Yak',
 'Kari Jobe - In The Name Of Love - Recorded At Spotify Studios NYC',
 'Weezer - O Come All Ye Faithful',
 'Wolfmother - Woman',
 'Bishop Briggs - Dark Side',
 'Los Prisioneros - Tren Al Sur',
 'Foo Fighters - Best of You',
 'Mastodon - Teardrinker',
 'The Score - Revolution',
 'The Seige - Run for Your Life',
 'Babasónicos - Deléctrico',
 "Type O Negative - I Don't Wanna Be Me",
 'Skay Beilinson - Aves Migratorias',
 'Estelares - Ríos de Lava',
 'Los Caligaris - Aunque No Quiero',
 'White Zombie - I\'m Your Boogieman - From "The Crow: City Of Angels" Soundtrack',
 'Molotov - Payaso',
 'Chris Tomlin - Joy To The World (Unspeakable Joy)',
 'Fernando Delgadillo - Noche Sin Luciérnagas',
 'Barns Courtney - Fire',
 'Patricio Rey y sus Redonditos de Ricota - Blues de la Artillería',
 'The Seige - I Am Defiant',
 'R.E.M. - Everybody Hurts',
 'Los Bunkers - Miño',
 'TobyMac & Leigh Nash - Christmas This Year',
 'Detonautas Roque Clube - Só por hoje / Tenis Roque',
 "Bishop Briggs - Dead Man's Arms",
 'Lifehouse - You And Me',
 'Los Caligaris - Olvidar',
 'The Score - The Fear',
 'O Rappa - Rodo cotidiano - Ao vivo',
 'KALEO - Save Yourself',
 'Nickelback - Far Away',
 'Red Hot Chili Peppers - Fire - Remastered',
 'Watt White - Eye Of The Storm',
 'Mazzy Star - Flowers In December',
 "Volbeat - The Devil's Bleeding Crown",
 'Red Hot Chili Peppers - The Drummer',
 "R.E.M. - It's The End Of The World As We Know It (And I Feel Fine)",
 'Slayer - Delusions of Saviour',
 'Red Hot Chili Peppers - Tippa My Tongue',
 'LCD Soundsystem - Daft Punk Is Playing at My House',
 'Korn - Rotting in Vain',
 'KALEO - All the Pretty Girls',
 'Red Hot Chili Peppers - Dark Necessities',
 'Soundgarden - Black Hole Sun',
 'Los Gardelitos - Sortilegio de Arrabal (En Vivo)',
 'Matt Redman - The Heart Of Worship',
 'Pescado Rabioso - Me Gusta Ese Tajo',
 'Grouplove - Tongue Tied',
 'Charlie Brown Jr. - O Preço - Ao Vivo',
 'Nirvana - Come As You Are',
 'Pato Fu - Sobre o Tempo',
 'Yeah Yeah Yeahs - Heads Will Roll',
 'Welshly Arms - Legendary',
 'Barns Courtney & Lennon Stella - Baby, It’s Cold Outside',
 'Rob Zombie - Living Dead Girl',
 'Los Abuelos De La Nada - Mil Horas',
 'Deftones - Ohms',
 'Weezer & AJR - All My Favorite Songs',
 'Estelares - Rimbaud',
 'The Killers & Armin van Buuren & Benno De Goeij - Human - Armin van Buuren Dub Remix',
 'Patricio Rey y sus Redonditos de Ricota - El Arte del Buen Comer',
 'NX Zero - Hoje O Céu Abriu',
 'Los Bunkers & Manuel García - Al Final De Este Viaje En La Vida',
 'Divididos - La Flor Azul',
 'Counting Crows - A Long December',

In [ ]:
# import json
# config_filename = 'config.json'
# # Writing the dictionary to a file in JSON format
# with open(config_filename, 'w') as config_file:
#     json.dump(mylist, config_file)

# print(f"Data successfully written to {config_filename}")
# pickle.dump(mylist, open('mylist.pkl','wb'))

In [ ]:
# use OneHotEncoding to make each genre into booleans 
genre_encoded = pd.get_dummies(df["genre"])

In [ ]:
features = df[[
    'danceability', 'energy', 'loudness', 'instrumentalness', 'tempo', 
    'key', 'mode', 'popularity'
    # ,'duration_ms'
]]

X = pd.concat([features, genre_encoded], axis=1)
df['genre'].unique()

array(['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient',
       'anime', 'black-metal', 'bluegrass', 'blues', 'brazil',
       'breakbeat', 'british', 'cantopop', 'chicago-house', 'children',
       'chill', 'classical', 'club', 'comedy', 'country', 'dance',
       'dancehall', 'death-metal', 'deep-house', 'detroit-techno',
       'disco', 'disney', 'drum-and-bass', 'dub', 'dubstep', 'edm',
       'electro', 'electronic', 'emo', 'folk', 'forro', 'french', 'funk',
       'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove',
       'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 'hardstyle',
       'heavy-metal', 'hip-hop', 'honky-tonk', 'house', 'idm', 'indian',
       'indie', 'indie-pop', 'industrial', 'iranian', 'j-dance', 'j-idol',
       'j-pop', 'j-rock', 'jazz', 'k-pop', 'kids', 'latin', 'latino',
       'malay', 'mandopop', 'metal', 'metalcore', 'minimal-techno', 'mpb',
       'new-age', 'opera', 'pagode', 'party', 'piano', 'pop', 'pop-film',
       'power-pop', 'progressive-house', 'psych-rock', 'punk',
       'punk-rock', 'r-n-b', 'reggae', 'reggaeton', 'rock', 'rock-n-roll',
       'rockabilly', 'romance', 'sad', 'salsa', 'samba', 'sertanejo',
       'show-tunes', 'singer-songwriter', 'ska', 'sleep', 'songwriter',
       'soul', 'spanish', 'study', 'swedish', 'synth-pop', 'tango',
       'techno', 'trance', 'trip-hop', 'turkish', 'world-music'],
      dtype=object)

In [ ]:
# drop rows with missing values (track_name)
# df = df.dropna(subset = ['track_name'])

In [ ]:
# make data into scaled bc knn depends on the distance
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
pickle.dump(X_scaled, open('pickle/X_scaled_smaller.pkl','wb'))

In [ ]:
# use euclidean distance

knn = NearestNeighbors(
    n_neighbors=10,
    metric="euclidean"
)

knn.fit(X_scaled)
pickle.dump(knn, open('pickle/knn_smaller.pkl','wb'))

In [ ]:
# lookup track by track_name
def get_song_index(song_name):
    return df[df["artist_track_name"] == song_name].index[0]

In [ ]:
# get la neighbors for that song
def get_neighbors(song_name):
    index = get_song_index(song_name)
    print(index)
    song_vector = X_scaled[index].reshape(1,-1)
    distances, indices = knn.kneighbors(song_vector)

    return distances[0], indices[0]

In [ ]:
def genre_bonus(index, song_A, song_B):
    genre_A = df[df["artist_track_name"] == song_A]["genre"].values[0]
    genre_B = df[df["artist_track_name"] == song_B]["genre"].values[0]

    genre_C = df.iloc[index]["genre"]

    bonus = 0

    if genre_C == genre_A:
        bonus += 0.1
    if genre_C == genre_B:
        bonus += 0.1

    return bonus

In [ ]:
def bridge_recommendation(song_A, song_B, top_n=5): 
    dist_A, ind_A = get_neighbors(song_A) # the distance and the independent variables chosen
    dist_B, ind_B = get_neighbors(song_B)

    scores = {}

    # convert those distances into similarity
    for d, i in zip(dist_A, ind_A):
        # scores[i] = scores.get(i, 0) + (1 / (1 + d)) # without the added weight of genre(OneHotEncoding)
        scores[i] = scores.get(i, 0) + (1 / (1 + d)) + genre_bonus(i, song_A, song_B)

    for d, i in zip(dist_B, ind_B):
        # scores[i] = scores.get(i, 0) + (1 / (1 + d))
        scores[i] = scores.get(i, 0) + (1 / (1 + d)) + genre_bonus(i, song_A, song_B)

    # sort by combined score
    sorted_songs = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    
    results = []
    for i, score in sorted_songs:
        name= df.iloc[i]["artist_track_name"]

        if name not in [song_A, song_B]:
            results.append((name, score))

    return results[:top_n]

In [ ]:
def normalize_scores(results):
    if not results:
        return []
    
    max_score = max(score for _, score in results)

    output = []
    for name, score in results:
        confidence = score / max_score
        output.append((name, score, confidence))

    return output

In [ ]:
song_1=df.sample(n=1)["artist_track_name"].values[0]
song_2=df.sample(n=1)["artist_track_name"].values[0]

print(song_1)
print(song_2)

Deluxe - Blue
Baron Vaughn - Baron Vaughn

In [ ]:
results = bridge_recommendation(song_1,song_2,4)
results

20987
3603

[('Larry The Cable Guy - Skeeters, Spiders and Lookalikes',
  np.float64(0.6840504657287757)),
 ('Rhod Gilbert - Escape to Afghanistan', np.float64(0.6140402554398546)),
 ('George Lopez - Chicano Dudes', np.float64(0.6026455859995494)),
 ('Stuart Thompson - Gun Range', np.float64(0.5996140511461078))]

In [ ]:
# import pickle
# model = pickle.load(open('model.pkl','rb'))
# model

In [ ]:
normalized_results = normalize_scores(results)
normalized_results

[('Larry The Cable Guy - Skeeters, Spiders and Lookalikes',
  np.float64(0.6840504657287757),
  np.float64(1.0)),
 ('Rhod Gilbert - Escape to Afghanistan',
  np.float64(0.6140402554398546),
  np.float64(0.8976534425507139)),
 ('George Lopez - Chicano Dudes',
  np.float64(0.6026455859995494),
  np.float64(0.8809957981060668)),
 ('Stuart Thompson - Gun Range',
  np.float64(0.5996140511461078),
  np.float64(0.8765640565821254))]

In [ ]:
# score is the raw value and confidence is the normalized value (0-1)
for name, score, confidence in normalized_results:
    print(f"{name} → Score: {score:.4f} | Confidence: {confidence:.2%}")

Larry The Cable Guy - Skeeters, Spiders and Lookalikes → Score: 0.6841 | Confidence: 100.00%
Rhod Gilbert - Escape to Afghanistan → Score: 0.6140 | Confidence: 89.77%
George Lopez - Chicano Dudes → Score: 0.6026 | Confidence: 88.10%
Stuart Thompson - Gun Range → Score: 0.5996 | Confidence: 87.66%