In [ ]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

In [ ]:
df = pd.read_csv("data/dataset_copy.csv").drop(["track_num"],axis=1).dropna(subset = ['track_name'])
df.head()

,track_id,artist_name,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson & ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [ ]:
df["artist_track_name"] = df["artist_name"] + " - "+ df["track_name"]
df

,track_id,artist_name,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre,artist_track_name
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,Gen Hoshino - Comedy
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,Ben Woodward - Ghost - Acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson & ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,Ingrid Michaelson & ZAYN - To Begin Again
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,Kina Grannis - Can't Help Falling In Love
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,...,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,Chord Overstreet - Hold On
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,...,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,Rainy Lullaby - Sleep My Little Boy
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,...,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,Rainy Lullaby - Water Into Light
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,...,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,Cesária Evora - Miss Perfumado
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,...,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,Michael W. Smith - Friends
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,...,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,Cesária Evora - Barbincor

In [ ]:
df.groupby('genre').sample('.2')

In [ ]:
df.drop_duplicates(subset=['artist_track_name'], keep=False)
pickle.dump(df, open('df_smaller.pkl','wb'))

In [ ]:
# since genre is in the form of different unique genres
mylist=df['artist_track_name'].to_list()
mylist = list(dict.fromkeys(mylist))
pickle.dump(mylist, open('mylist_smaller.pkl','wb'))
mylist

['Gen Hoshino - Comedy',
 'Ben Woodward - Ghost - Acoustic',
 'Ingrid Michaelson & ZAYN - To Begin Again',
 "Kina Grannis - Can't Help Falling In Love",
 'Chord Overstreet - Hold On',
 'Tyrone Wells - Days I Will Remember',
 'A Great Big World & Christina Aguilera - Say Something',
 "Jason Mraz - I'm Yours",
 'Jason Mraz & Colbie Caillat - Lucky',
 'Ross Copperman - Hunger',
 'Zack Tabudlo - Give Me Your Forever',
 "Jason Mraz - I Won't Give Up",
 'Dan Berk - Solo',
 'Anna Hamilton - Bad Liar',
 'Chord Overstreet & Deepend - Hold On - Remix',
 'Landon Pigg - Falling in Love at a Coffee Shop',
 'Andrew Foy & Renee Foy - ily (i love you baby)',
 'Andrew Foy & Renee Foy - At My Worst',
 'Boyce Avenue & Bea Miller - Photograph',
 'Boyce Avenue & Jennel Garcia - Demons',
 'Jason Mraz - 93 Million Miles',
 'Jason Mraz - Unlonely',
 'Jason Mraz - Bella Luna',
 'Jason Mraz - Winter Wonderland',
 'Jason Mraz - If It Kills Me',
 'Chord Overstreet - All I Want For Christmas Is A Real Good Tan',
 'Brandi Carlile & Sam Smith - Party of One',
 'KT Tunstall - Lonely This Christmas',
 'Brandi Carlile - Throwing Good After Bad',
 'Brandi Carlile - This Time Tomorrow',
 'Eddie Vedder - The Haves',
 "Brandi Carlile - When You're Wrong",
 'Brandi Carlile & Lucius - You and Me on the Rock',
 'Brandi Carlile - Speak Your Mind (From the Netflix Series "We The People")',
 'Highland Peak - Trampoline - Acoustic',
 'Motohiro Hata - 透明だった世界',
 'Andrew Belle - Pieces',
 'Ron Pope - A Drop in the Ocean',
 'Adam Christopher - So Far Away - Acoustic',
 'Andrew Belle - The Enemy',
 'Aron Wright - Build It Better',
 'Chord Overstreet - Sleepwalking in the Rain',
 'Sara Bareilles - Gravity',
 "Chord Overstreet - What's Left of You",
 'Zack Tabudlo - Pano',
 "Andrew Belle - Sky's Still Blue",
 'Kurt Cobain - And I Love Her',
 "Boyce Avenue & Bea Miller - We Can't Stop",
 'Tim Halperin - Always Be My Baby',
 'Canyon City - Alone with You',
 'Aaron Espe - Making All Things New',
 'Sara Bareilles - She Used To Be Mine',
 'Andrew Belle - In My Veins - Feat. Erin Mccarley',
 "Tyler Ward - I Don't Wanna Live Forever (Fifty Shades Darker)",
 'Ron Pope - A Drop In the Ocean',
 "Five For Fighting - Superman (It's Not Easy)",
 'Andrew Belle - When the End Comes',
 "Bailey Jehl - You're Still The One",
 'Ingrid Michaelson - Light Me Up',
 'A Great Big World - Kaleidoscope',
 'Eddie Vedder & Nusrat Fateh Ali Khan - The Long Road',
 'Drew Holcomb & The Neighbors - What Would I Do Without You',
 'Jason Mraz - Have It All',
 'Gabrielle Aplin - Heavy Heart',
 'Gabrielle Aplin - The House We Never Built',
 'Eddie Vedder - Society',
 "Gabrielle Aplin - Please Don't Say You Love Me",
 'Eddie Vedder - Guaranteed',
 'Sara Bareilles - Brave',
 'Five For Fighting - Heaven Knows',
 'The Civil Wars - I Heard The Bells On Christmas Day',
 'KT Tunstall - Fairytale Of New York',
 'KT Tunstall - Hold On',
 'KT Tunstall - Suddenly I See',
 'Motohiro Hata - Rain',
 'Callum J Wright - Somebody Else - Acoustic',
 'Andrew Belle - Pieces (Hushed)',
 'Boyce Avenue & Fifth Harmony - Mirrors',
 'Boyce Avenue - Stand by Me',
 'Gabrielle Aplin & JP Cooper - Losing Me',
 'Mone Kamishiraishi - なんでもないや - movie ver.',
 'John Adams - You’re Beautiful - Acoustic',
 'Kitri - Hikare Inochi',
 'Tyler Ward - How To Lose a Girl',
 'Boyce Avenue - Can’t Help Falling in Love',
 'Andrew Belle - Dive Deep (Hushed)',
 "Ben Woodward - When the Party's over (Acoustic Piano)",
 'Augustana - Boston',
 'Matthew Perryman Jones - Living in the Shadows',
 'Boyce Avenue - In Case You Didn’t Know',
 'Andrew Foy & Renee Foy - death bed (coffee for your head)',
 'Kina Grannis - You Are My Sunshine',
 'Ray LaMontagne & Sierra Ferrell - I Was Born To Love You',
 'Meg Birch - Only Love Can Hurt Like This',
 'Catherine Feeny - Mr Blue',
 'Joshua Hyslop - Do Not Let Me Go',
 'Ross Copperman - Holding On And Letting Go',
 'JJ Heller - You Already Know',
 'Ben Woodward - Believer (Remix)',
 'Howie Day - Collide - Acoustic Version',
 'Ben Rector - Love Like This',
 'Matt Nathanson - Come On Get Higher',
 'Rachael Yamagata - "Something In the Rain" (Something In the Rain, Pt. 1) [Music from the Original TV Series]',
 'Parachute - Kiss Me Slowly',
 'Parachute - Without You',
 'Jason Mraz - Absolutely Zero',
 'Jason Mraz - Sleep All Day',
 'Jason Mraz - You and I Both',
 'Eddie Vedder - Long Nights',
 'Jason Mraz - Who Needs Shelter',
 'Jason Mraz - No Stopping Us',
 "Jason Mraz - I'll Do Anything",
 'JJ Heller - Make You Feel My Love',
 "Jason Mraz - The Remedy (I Won't Worry)",
 'Jason Mraz - Too Much Food',
 "Jason Mraz - The Boy's Gone",
 'Jason Mraz - On Love, in Sadness',
 'Jason Mraz - Curbside Prophet',
 'Jason Mraz - Tonight, Not Again - Live',
 'Jason Mraz - Tonight, Not Again',
 'Eddie Vedder - Hard Sun',
 'Susie Suh & Robot Koch - Here with Me',
 'Tyler Ward & Lindsey Stirling & Kina Grannis - The Scientist',
 'Howie Day - Collide',
 'Eden Elf & Ren Avel - get better',
 'Kitri - Sympathy',
 'Boyce Avenue & Rachel Grae - Let It Go',
 'Chord Overstreet - What You Need',
 'Five For Fighting - 100 Years',
 "Andrew Belle - You're the Sea",
 'Rachael Yamagata - No Direction',
 'Cary Brothers - Belong',
 'The Mayries - As It Was',
 'Joseph Sullinger - Chi Mai',
 'Parachute - Had It All',
 'Zack Tabudlo & Yonnyboii - Take Me Back ft. Yonnyboii',
 'Tobey Rosen - Whole Again - Acoustic Version',
 'The Mayries - Overpass Graffiti',
 'Sara Bareilles - Love Song',
 'Andrew Foy & Renee Foy - Let Her Go',
 'Aqualung - Brighter Than Sunshine',
 'Tyler Ward & Karis & Ray Lorraine - Love Story',
 'Agustín Amigó & Nylonwings - Mujer con Abanico',
 'Amy Stroup - In the Shadows',
 'Boyce Avenue & Connie Talbot - Can You Feel the Love Tonight',
 'Brandi Carlile - The Story',
 'JJ Heller - Better',
 'Kina Grannis - Iris',
 'The Mayries - Rockabye - Acoustic Version',
 'Caleb Santos & Viva Music Publishing Inc. - I Need You More Today',
 'Boyce Avenue - Beautiful Soul',
 "Jason Mraz - Let's See What The Night Can Do",
 'Rachael Yamagata - La La La (Something In the Rain, Pt. 2) [Music from the Original TV Series]',
 'Parachute - Forever And Always',
 'Priscilla Ahn - Fine On The Outside',
 'Chord Overstreet - Tortured Soul',
 'JJ Heller - I Believe in You',
 'Jon Bryant - At Home',
 'Donovan Woods - Portland, Maine',
 'Ross Copperman - Holding On and Letting Go',
 'Joshua Hyslop - The Flood',
 'Angelina Cruz - Hanggang Kailan (Umuwi Ka Na Baby)',
 'Stephen Speaks - Out of My League',
 'A Great Big World - Say Something',
 'Eddie Vedder - Rise',
 'The Weepies & Deb Talan & Steve Tannen - World Spins Madly On',
 'Freddie King - Stumble',
 'Taj Mahal - Paradise',
 "Keb' Mo' & Gerald Albright - Moonlight, Mistletoe & You",
 'Motohiro Hata - ひまわりの約束',
 'Thomas Daniel - Since U Been Gone - Acoustic Version',
 'Masayoshi Yamazaki - One more time,One more chance',
 'Kina Grannis - Creep',
 'Todd Carey & Ariza & Chuck Leavell - Higher Love',
 'YUZU - Hyouriittai',
 'Canyon City - How Long Will I Love You',
 'Zack Tabudlo - Binibini',
 'Aron Wright - You Were Supposed to Be Different',
 'Boyce Avenue - Thinking out Loud',
 'Jonah Baker - Perfect / Style',
 'The Civil Wars - Poison & Wine',
 'Ingrid Michaelson - You And I',
 'Zack Tabudlo & Billkin - Give Me Your Forever (ft. Billkin)',
 'Anna Nalick - Breathe (2 AM)',
 'Zack Tabudlo - Habang Buhay',
 'Jonah Baker - Beautiful Soul',
 'Ben Woodward - Bulletproof',
 'Andrew Belle - Spectrum',
 'Jonah Baker - Girls Like You - Acoustic Version',
 'Zack Tabudlo - Nangangamba',
 'Us The Duo - Better Together',
 'Andrew Foy & Renee Foy - Heartbreak Anniversary',
 'Tyler Ward & Karis & Ray Lorraine - One More Time Around',
 'Zack Tabudlo - Heart Can’t Lose',
 "Donovan Woods & Tenille Townes - I Ain't Ever Loved No One - Acoustic",
 'Ray LaMontagne - Empty',
 'Megan Davies - See You Again, Love Me Like You Do, Sugar - Acoustic Mashup',
 'Tim Halperin - The Reason',
 'Canyon City - Fix You',
 'JJ Heller - Hand to Hold',
 'Ray LaMontagne - Hold You in My Arms',
 'Us The Duo - One Last Dance',
 'Boyce Avenue & Megan Nicole - Heaven',
 'Joshua Hyslop - The Spark - Bonus Track',
 'Drew Holcomb & The Neighbors - American Beauty',
 'Ray LaMontagne - Such A Simple Thing',
 'Amos Lee - Colors',
 'Boyce Avenue - Someone You Loved',
 'Jason Mraz & Meghan Trainor - More Than Friends (feat. Meghan Trainor)',
 'Days N Daze - Flurry Rush',
 'Sara Bareilles - I Choose You',
 'Mindy Gledhill - I Do Adore',
 "Dave Barnes - I'll Be Home For Christmas",
 'Get Dead - Fuck You',
 'Albert King - Christmas Comes But Once A Year',
 "John Adams - If I Ain't Got You - Acoustic",
 'John Adams - Believe - Acoustic',
 'Adam Christopher - Iris - Acoustic',
 'Motohiro Hata - Rain - Long Ver.',
 "Aoi Teshima - C'est si bon",
 'Jonah Baker - Baby (Acoustic Version)',
 'YUZU - Reason',
 'Boyce Avenue & Emma Heesters - I Like Me Better',
 'Zack Tabudlo - Asan Ka Na Ba',
 'Boyce Avenue - A Thousand Years',
 'Thomas Daniel - drivers license',
 'Jason Mraz - Love Someone',
 'Jae Hall - The Winner Takes It All - Acoustic',
 'Aaron Espe - Only Time',
 'A Fine Frenzy - Almost Lover',
 'Roses & Frey - Dance Monkey',
 'Parachute - Ocean',
 'Kina Grannis - Dream a Little Dream of Me',
 'The Mayries - Back For Good',
 'Canyon City - OK',
 'Andrew Foy & Renee Foy - Just The Two Of Us',
 'Boyce Avenue - Hey There Delilah',
 'Andrew Foy & Renee Foy - Arcade',
 'Kina Grannis - Yellow',
 'Roses & Frey - Wake Me Up',
 'Aidan Hawken - Walking Blind',
 'Jon Bryant - Headphones',
 'The Rescues - Teenage Dream',
 'Ivan & Alyosha - The Worth Of The Wait',
 "Kina Grannis - Can't Help Falling In Love - Piano Version",
 'Austin Plaine - Never Come Back Again',
 'Chord Overstreet - Love You To Death',
 'Plamina - Someone You Loved - Acoustic',
 'Kina Grannis & Imaginary Future - What a Wonderful World',
 'Andrew Foy & Renee Foy - You Broke Me First',
 'Joshua Hyslop - Long Way Down',
 'Parachute - She Is Love',
 'Phillip LaRue - Marigold',
 'krissy & ericka - 12:51',
 'Takehara Pistol - サンサーラ',
 'Allman Brown & Liz Lawrence - Sons and Daughters',
 'Ben Rector - Brand New',
 'The Weepies & Deb Talan & Steve Tannen - Gotta Have You',
 'Ben Rector - 30,000 Feet',
 'Eddy Tyler - A Thousand Years',
 'Ray LaMontagne - Jolene',
 'Eddie Vedder - No Ceiling',
 'Joy Williams - Front Porch',
 'Days N Daze - Goodbye Lulu',
 'Ray LaMontagne - Three More Days',
 "Callum J Wright - Isn't She Lovely - Acoustic",
 'Rachael Yamagata - We Could Still Be Happy',
 'John Adams - Fix You - Acoustic',
 "Lusaint - I'm Yours - Acoustic",
 'Boyce Avenue & Sarah Hyland - Closer',
 "Mother's Daughter & Beck Pete - A Sky Full of Stars",
 "Aron Wright - I Don't Believe in Satan",
 'The Perishers - Pills',
 'Tyler Ward & Madysyn - Shallow - Acoustic',
 'Jonah Baker - Watermelon Sugar - Acoustic',
 "Matt Johnson & Jaclyn Davies - Say You Won't Let Go - Acoustic",
 'Ben Woodward - Call You Mine (Acoustic Piano)',
 'Kina Grannis - For Now',
 'Greg Laswell - Sweet Dream',
 'Andrew Foy - Love Nwantiti',
 'Ross Copperman - Stars Are on Your Side',
 "Jonah Baker & Sara Phillips - We Don't Talk Anymore / Cold (feat. Sara Phillips)",
 'Joe Brooks - Superman',
 'Boyce Avenue - Chasing Cars',
 'Zack Tabudlo - Calm Me Down',
 'Masaharu Fukuyama - KISSして',
 'Zack Tabudlo & James TW - Binibini (Last Day On Earth) (feat. James TW)',
 'Ciaran Lavery - Left for America',
 'John Frusciante - Ramparts',
 'Chord Overstreet - Hold On - Acoustic',
 'The Civil Wars - Dust to Dust',
 'Masaharu Fukuyama - Good night',
 'Zack Tabudlo - As You Are',
 'Sara Farell - It Aint Me',
 'Ingrid Michaelson & AJR - The Lotto',
 'Rodrigo y Gabriela - Tamacun',
 'Andrew Belle - Make It Without You',
 'Priscilla Ahn - Dream',
 'JJ Heller - Big Love, Small Moments',
 'Priscilla Ahn - I Am Not Alone',
 'Joshua Hyslop - Stand Your Ground',
 'Front Porch Step - Perfect Man',
 'Takehara Pistol - あ。っという間はあるさ',
 'Eric Hutchinson - Tell The World',
 "Brett Dennen - Ain't No Reason",
 'Rail Yard Ghosts - A Month from Now',
 'Five For Fighting - What If',
 'The Bridge City Sinners - Pussy Cat',
 'Frank Turner - Polaroid Picture',
 'Matt Costa - I Bet On Flying High',
 'Jonah Baker - Mirrors - Acoustic',
 'Aqualung & Kina Grannis - To the Wonder (feat. Kina Grannis)',
 'Jonah Baker - Stay - Acoustic',
 'Ichiko Aoba - 太陽さん',
 'Kina Grannis - Oh What A Love',
 'Meiko - Leave The Lights On',
 "Erin McCarley - I Won't Let You Down",
 'Jason Mraz - Look For The Good (Single Version)',
 'Isabella Celander - Stargazing',
 'Roses & Frey - Bad Liar',
 'Rachael Yamagata - Is It You',
 'Us The Duo - Slow Down Time',
 'Amber Leigh Irish - 2002 - Acoustic',
 'Jess Penner - Sweeter',
 'Daniel Robinson - Heat Waves - Acoustic',
 'Yosui Inoue & Tamio Okuda - アジアの純真',
 'Jonah Baker & Celine - If the World Was Ending - Acoustic',
 'Greg Laswell - Comes And Goes (In Waves)',
 'Masaharu Fukuyama - ながれ星',
 'Blame Jones - Dusk Till Dawn - Acoustic',
 "Ben Woodward - Don't Wanna Leave You",
 'Stephen Speaks - Passenger Seat',
 'Matt White - Love',
 'Boyce Avenue - Hallelujah',
 'Madi Diaz - Ashes',
 'Masaharu Fukuyama - 明日の☆SHOW',
 'Boyce Avenue - Love Me Like You Do',
 'Canyon City - Lost Sparks',
 'Tristan Prettyman - Who We Are',
 'Masaharu Fukuyama - Heart (Original Version)',
 "JJ Heller - It'll Be Alright",
 'Ingrid Michaelson - Everybody',
 'Mark Oblea - Kabilugan Ng Buwan',
 'Ingrid Michaelson - Keep Breathing',
 'Boyce Avenue & Kina Grannis - Fast Car',
 'Boyce Avenue - Just the Way You Are',
 'Andrew Belle - The Ladder',
 'Masaharu Fukuyama - HELLO (Original Version)',
 'Hanare Gumi - 接吻',
 "Brett Dennen & Benedict Cumberbatch - Can't Keep It Inside",
 'Hanare Gumi - 明日天気になれ',
 "Masaharu Fukuyama - IT'S ONLY LOVE",
 'Masaharu Fukuyama - それがすべてさ',
 "A Great Big World - I Don't Wanna Love Somebody Else",
 'RENT STRIKE - Burn It All!',
 'Brandi Carlile - Carried Me With You',
 'Mischief Brew - O, Pennsyltucky!',
 'Frank Turner - I Believed You, William Blake',
 'Get Dead - Pepperspray',
 'Get Dead - Stickup',
 'Grace George - Heaven - Acoustic',
 "Jack Savoretti - Soldier's Eyes",
 'Ichiko Aoba - Asleep Among Endives',
 'Thomas Daniel - Symphony - Acoustic',
 'Boyce Avenue & Fifth Harmony - When I Was Your Man',
 'Amber Leigh Irish - Save Your Tears - Acoustic',
 'Gen Hoshino - Koi',
 'Richard Walters - July Bones',
 'Kaiak & Viktoria Tolstoy - Autumn Breeze',
 'Boyce Avenue - Save Your Tears',
 "Bailey Rushlow - You're Still The One - Acoustic",
 'Kina Grannis - Somebody Loved',
 'Boyce Avenue - Rise',
 'John Adams - Bohemian Rhapsody - Acoustic',
 'Amber Leigh Irish - As It Was - Acoustic',
 'Canyon City - Wish List',
 'Chord Overstreet - Beautiful Disaster',
 'Wayne Mack - Fake a smile',
 'Aimyon - Marigold',
 'Sungha Jung - River Flows In You',
 'Tamio Okuda - Kill Me Pretty',
 'Us The Duo - No Matter Where You Are',
 'Ben Rector - I Like You',
 'Parachute - The Mess I Made',
 'Zee Avi - Dream a Little Dream of Me',
 'Joshua Radin - Here, Right Now',
 'Boyce Avenue - Wonderful Tonight',
 'Gabrielle Aplin - Salvation',
 'Jon Bryant - Wilderness',
 'Masaharu Fukuyama - 恋人 (Original Version)',
 'Bailey Pelkman & Randy Rektor - I Just Called To Say I Love You',
 'A Great Big World & Christina Aguilera - Fall on Me',
 "John Frusciante - Song To Sing When I'm Lonely",
 'Tres Hermanas - Have Yourself a Merry Little Christmas',
 'Masaharu Fukuyama - Message (Original Version)',
 'Matt Johnson - Beautiful In White',
 'The Mayries - Heaven Is a Place on Earth',
 'Stephen Speaks - Passenger Seat (Acoustic)',
 'Eddie Vedder - Guaranteed - Humming Version',
 'Dave Van Ronk - Hang Me, Oh Hang Me',
 'John Frusciante & Josh Klinghoffer - The Afterglow',
 'Frank Turner - Eat the Meek',
 'Joy Williams - The Trouble with Wanting',
 'Ray LaMontagne - You Are the Best Thing',
 'Mischief Brew - Boycott Me!',
 'Days N Daze & Freddie Boatright - To Risk to Live',
 'The Bridge City Sinners - The Legend of Olog-hai, Pt. 1',
 'Zee Avi - No Christmas For Me',
 "Get Dead - This One's for Johnny",
 'Highland Peak - Graveyard - Acoustic',
 'Ichiko Aoba - bouquet',
 'Aoi Teshima - こころをこめて',
 'AcousticTrench - Paradise',
 'Parachute - Better',
 'Matt Nathanson - Laid',
 'Lee DeWyze - Same For You',
 'Clementine Duo - 2U - Acoustic Version',
 'Rachael Yamagata - Duet',
 "Brandon Chase - I'll Say I Do",
 'Bailey Jehl - Anyone',
 'Gabrielle Aplin - Start of Time',
 'Bailey Jehl - Heat Waves',
 'Clementine Duo - There She Goes',
 'Joshua Hyslop - Wells',
 'Kina Grannis & Imaginary Future - God Only Knows',
 'Andrew Foy & Renee Foy - Afterglow',
 'Kurt Cobain - Burn The Rain',
 'Us The Duo - Already Mine',
 'Hanare Gumi - きみはぼくのともだち',
 'Gabrielle Aplin - Never Be the Same',
 'Austin Basham - All Is Well',
 'Gabrielle Aplin - My Mistake',
 'Us The Duo - Near Or Far',
 'Drew Holcomb & The Neighbors - Without a Light',
 'Parachute - Lonely With Me',
 'Boyce Avenue & Megan Davies & Jaclyn Davies - Time After Time',
 'Eastmountainsouth - So Are You To Me',
 'Peter Bradley Adams - My Arms Were Always Around You',
 'The Civil Wars - Dance Me to the End of Love - Bonus',
 'Eddie Vedder - Photographs',
 'Suy Galvez - Baby Now That I Found You',
 'Suy Galvez - Right Here Waiting',
 "Howlin' Wolf - Smokestack Lightnin'",
 'Buddy Guy & Bonnie Raitt - Feels Like Rain (feat. Bonnie Raitt)',
 'Mance Lipscomb - Sugar Babe',
 'Violent Femmes - Blister In The Sun',
 'Days N Daze - Little Blue Pills, Pt. 2',
 "Drei Rana & Selena Marie - Paano Ang Simbang Gabi - Kung 'Di Ka Katabi",
 'Frank Turner - Bob',
 'Harley Poe - Psycho',
 'Frank Turner - Perfect Government',
 'The Bridge City Sinners - The Fear',
 'Ben Rector - Living My Best Life',
 "Frank Turner - Haven't Been Doing So Well",
 'The Bridge City Sinners - The Legend of Olog-hai, Pt. 2',
 'Brandi Carlile & Lucius - You and Me On The Rock (feat. Lucius)',
 'Get Dead - Glitch',
 'Jonah Baker - A Thousand Years - Acoustic',
 'Trevor Hall & Marieme - 2 Oceans',
 'Ben Woodward - Golden Hour - Acoustic Piano',
 'Brandon Chase - Without Me',
 'Aron Wright - You & Me (The Wildfire)',
 'Sara Farell - Dancing With A Stranger',
 'Zack Tabudlo - Pero',
 'Jonah Baker - Good 4 U (Acoustic)',
 'Greg Laswell - And Then You',
 'Daniel Robinson - Here With Me - Acoustic',
 "Boyce Avenue - I'll Be There For You (Friends Theme)",
 'Gabrielle Aplin - So Far so Good',
 'Colin & Caroline - More Than Gravity',
 'Andrew Belle - Fade into You',
 'Masaharu Fukuyama - 東京にもあったんだ',
 'Masaharu Fukuyama - あの夏も 海も 空も',
 'Bailey Jehl - 21 Guns',
 'Canyon City - Waves',
 'Jonah Baker - Running Up That Hill (A Deal With God) - Acoustic',
 "Kurt Cobain - Poison's Gone",
 'Masaharu Fukuyama - 18 ~eighteen~',
 'Kina Grannis - Build Me Up Buttercup',
 'The Mayries - Umbrella - Acoustic Version',
 'Gabrielle Aplin - Home',
 "Joshua Radin - You're My Home",
 'Masaharu Fukuyama - vs.2013 ~知覚と快楽の螺旋~',
 'Ysabelle Cuevas - I Like Me Better',
 'Bailey Pelkman & Randy Rektor - Something Stupid',
 'Ethan Loukas & Janine Teñoso - Hanap-Hanap',
 'John Frusciante - The Will To Death',
 'Adam Christopher - Boulevard of Broken Dreams (Acoustic)',
 'Penny and Sparrow - Eloise',
 'Sonny Boy Williamson II - Help Me',
 'Shannon & Keast - Everytime We Touch (Acoustic)',
 'Ray LaMontagne - Let It Be Me',
 'Mia Rollo - Beer',
 'Boyce Avenue - Someone Like You',
 "Suy Galvez - You've Got a Friend",
 'JJ Heller - This Little Light of Mine',
 'Takehara Pistol - Amazing Grace',
 'Days N Daze - Remnants of What People Used to Be',
 'AJJ - Linda Ronstadt',
 'SANNA NORTH - Unsteady - Acoustic Covers Versions of Popular Songs',
 "Brandi Carlile - Heart's Content",
 'The Bridge City Sinners - The Damned',
 'Pigeon Pit - Hot Knives',
 'Get Dead - Nickel Plated',
 'Adam Christopher - Peaches - Acoustic',
 'A Great Big World - You',
 'Andrew Belle - Swimmers',
 "Kris Allen - Live Like We're Dying",
 'Lúc - Somebody That I Used To Know',
 'Ben Woodward - Lost Without You',
 'Masayoshi Yamazaki - One more time, One more chance',

In [ ]:
# import json
# config_filename = 'config.json'
# # Writing the dictionary to a file in JSON format
# with open(config_filename, 'w') as config_file:
#     json.dump(mylist, config_file)

# print(f"Data successfully written to {config_filename}")
# pickle.dump(mylist, open('mylist.pkl','wb'))

In [ ]:
# use OneHotEncoding to make each genre into booleans 
genre_encoded = pd.get_dummies(df["genre"])

In [ ]:
features = df[[
    'danceability', 'energy', 'loudness', 'instrumentalness', 'tempo', 
    'key', 'mode', 'popularity'
    # ,'duration_ms'
]]

X = pd.concat([features, genre_encoded], axis=1)
df['genre'].unique()

array(['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient',
       'anime', 'black-metal', 'bluegrass', 'blues', 'brazil',
       'breakbeat', 'british', 'cantopop', 'chicago-house', 'children',
       'chill', 'classical', 'club', 'comedy', 'country', 'dance',
       'dancehall', 'death-metal', 'deep-house', 'detroit-techno',
       'disco', 'disney', 'drum-and-bass', 'dub', 'dubstep', 'edm',
       'electro', 'electronic', 'emo', 'folk', 'forro', 'french', 'funk',
       'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove',
       'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 'hardstyle',
       'heavy-metal', 'hip-hop', 'honky-tonk', 'house', 'idm', 'indian',
       'indie-pop', 'indie', 'industrial', 'iranian', 'j-dance', 'j-idol',
       'j-pop', 'j-rock', 'jazz', 'k-pop', 'kids', 'latin', 'latino',
       'malay', 'mandopop', 'metal', 'metalcore', 'minimal-techno', 'mpb',
       'new-age', 'opera', 'pagode', 'party', 'piano', 'pop-film', 'pop',
       'power-pop', 'progressive-house', 'psych-rock', 'punk-rock',
       'punk', 'r-n-b', 'reggae', 'reggaeton', 'rock-n-roll', 'rock',
       'rockabilly', 'romance', 'sad', 'salsa', 'samba', 'sertanejo',
       'show-tunes', 'singer-songwriter', 'ska', 'sleep', 'songwriter',
       'soul', 'spanish', 'study', 'swedish', 'synth-pop', 'tango',
       'techno', 'trance', 'trip-hop', 'turkish', 'world-music'],
      dtype=object)

In [ ]:
# drop rows with missing values (track_name)
# df = df.dropna(subset = ['track_name'])

In [ ]:
# make data into scaled bc knn depends on the distance
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
pickle.dump(X_scaled, open('X_scaled_smaller.pkl','wb'))

In [ ]:
# use euclidean distance

knn = NearestNeighbors(
    n_neighbors=10,
    metric="euclidean"
)

knn.fit(X_scaled)
pickle.dump(knn, open('knn_smaller.pkl','wb'))

In [ ]:
# lookup track by track_name
def get_song_index(song_name):
    return df[df["artist_track_name"] == song_name].index[0]

In [ ]:
# get la neighbors for that song
def get_neighbors(song_name):
    index = get_song_index(song_name)
    song_vector = X_scaled[index].reshape(1,-1)
    distances, indices = knn.kneighbors(song_vector)

    return distances[0], indices[0]

In [ ]:
def genre_bonus(index, song_A, song_B):
    genre_A = df[df["artist_track_name"] == song_A]["genre"].values[0]
    genre_B = df[df["artist_track_name"] == song_B]["genre"].values[0]

    genre_C = df.iloc[index]["genre"]

    bonus = 0

    if genre_C == genre_A:
        bonus += 0.1
    if genre_C == genre_B:
        bonus += 0.1

    return bonus

In [ ]:
def bridge_recommendation(song_A, song_B, top_n=5): 
    dist_A, ind_A = get_neighbors(song_A) # the distance and the independent variables chosen
    dist_B, ind_B = get_neighbors(song_B)

    scores = {}

    # convert those distances into similarity
    for d, i in zip(dist_A, ind_A):
        # scores[i] = scores.get(i, 0) + (1 / (1 + d)) # without the added weight of genre(OneHotEncoding)
        scores[i] = scores.get(i, 0) + (1 / (1 + d)) + genre_bonus(i, song_A, song_B)

    for d, i in zip(dist_B, ind_B):
        # scores[i] = scores.get(i, 0) + (1 / (1 + d))
        scores[i] = scores.get(i, 0) + (1 / (1 + d)) + genre_bonus(i, song_A, song_B)

    # sort by combined score
    sorted_songs = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    
    results = []
    for i, score in sorted_songs:
        name= df.iloc[i]["artist_track_name"]

        if name not in [song_A, song_B]:
            results.append((name, score))

    return results[:top_n]

In [ ]:
def normalize_scores(results):
    if not results:
        return []
    
    max_score = max(score for _, score in results)

    output = []
    for name, score in results:
        confidence = score / max_score
        output.append((name, score, confidence))

    return output

In [ ]:
results = bridge_recommendation("Alan Walker - Faded - Lost Stories Remix", "Caravan Palace - Lone Digger",4)
results

[('Snakehips & ZAYN - Cruel (feat. ZAYN)', np.float64(0.6153777596535086)),
 ('Shankar & Ehsaan & Loy & Sonu Nigam & Mahalakshmi Iyer & Gulzar - Chup Chup Ke',
  np.float64(0.5616139789881384)),
 ('DJ Snake & Marshmello & Justin Bieber - Let Me Love You - Marshmello Remix',
  np.float64(0.5515142564478743)),
 ('Dimitri Vegas & Like Mike & David Guetta & Dimitri Vegas & Kiiara - Complicated (feat. Kiiara)',
  np.float64(0.5422857820874059))]

In [ ]:
# import pickle
# model = pickle.load(open('model.pkl','rb'))
# model

In [ ]:
normalized_results = normalize_scores(results)
normalized_results

[('Snakehips & ZAYN - Cruel (feat. ZAYN)',
  np.float64(0.6153777596535086),
  np.float64(1.0)),
 ('Shankar & Ehsaan & Loy & Sonu Nigam & Mahalakshmi Iyer & Gulzar - Chup Chup Ke',
  np.float64(0.5616139789881384),
  np.float64(0.9126328830998992)),
 ('DJ Snake & Marshmello & Justin Bieber - Let Me Love You - Marshmello Remix',
  np.float64(0.5515142564478743),
  np.float64(0.8962206511304651)),
 ('Dimitri Vegas & Like Mike & David Guetta & Dimitri Vegas & Kiiara - Complicated (feat. Kiiara)',
  np.float64(0.5422857820874059),
  np.float64(0.8812242132259418))]

In [ ]:
# score is the raw value and confidence is the normalized value (0-1)
for name, score, confidence in normalized_results:
    print(f"{name} → Score: {score:.4f} | Confidence: {confidence:.2%}")

Snakehips & ZAYN - Cruel (feat. ZAYN) → Score: 0.6154 | Confidence: 100.00%
Shankar & Ehsaan & Loy & Sonu Nigam & Mahalakshmi Iyer & Gulzar - Chup Chup Ke → Score: 0.5616 | Confidence: 91.26%
DJ Snake & Marshmello & Justin Bieber - Let Me Love You - Marshmello Remix → Score: 0.5515 | Confidence: 89.62%
Dimitri Vegas & Like Mike & David Guetta & Dimitri Vegas & Kiiara - Complicated (feat. Kiiara) → Score: 0.5423 | Confidence: 88.12%